### PR TITLE
Fix profiling when python symbols aren't available.

### PR DESCRIPTION
**Pull request by benfred**
Since python 3.10 - we haven't been able to profile python interpreters that have been compiled without symbols. This is because cpython changed where the 'PyRuntime' global is stored in python 3.10, from being in the BSS section into being in its own named section in the binary (https://github.com/python/cpython/pull/4802)

This especially affected profiling on windows, where you'd have to install python symbols to be able to use py-spy.

Fix by reading in the address/size of the the PyRuntime section from the elf/mach/pe binaries and using that to scan python interpreters when symbols aren't available.

### CODE REVIEW

**Comment by zanieb** [comment]
I believe you can also test this with the "stripped" variants of `python-build-standalone` (which uv installs by default)

**Comment by benfred** [comment]
it would be pretty cool if we could test this out using a stripped build in CI - does the uv build strip out the PyRuntime symbol too ? (like what does something like `nm -A `which python` | grep PyRuntime` show ?)

In the short term, I'm testing this by verifying this fixes the windows wheels https://github.com/benfred/py-spy/pull/543 - since this mostly impacts windows right now

**Comment by benfred** [comment]
I've created https://github.com/benfred/py-spy/issues/719 to track testing this functionality in CI - but I'm going to merge this change in now since it does fix the issue , and I've tested this manually to verify it works (and I'd like to get a release out with =)

**Comment by fleimgruber** [comment]
@benfred Just a quick heads-up on https://github.com/benfred/py-spy/pull/718#issuecomment-2451054736:

I am still seeing #593.
I tried with a Python installed by uv and got:

```
/usr/bin/nm: /c/Users/LeimgruberF/lg/.venv/Scripts/python: no symbols
```

This is on Windows (using `nm` from MSYS2 MinGW64).

**Pull request merged**
