### PR TITLE
Fix for venv in Windows 10, try several times to get the process' children

### PR DESCRIPTION
**Pull request by IceTDrinker**
- allows to profile venv python when using the subprocess (-s) flag

solves https://github.com/benfred/py-spy/issues/216

### CODE REVIEW

**Comment by IceTDrinker** [comment]
This is dirty, but I don't know if there is a way to wait for a Windows process to say it has children processes, improvements welcome but it does the (dirty) trick on my win 10

Cheers

**Comment by IceTDrinker** [comment]
Gentle ping @benfred sorry if that's not the way to request a review, I can't seem to request them on the PR.

Cheers

**Comment by benfred** [comment]
Thanks for the PR! I'm glad that you figured out what the issue is with profiling windows venvs.

I like the idea of retrying if we can't find any python processes - but my one issue with this PR is that it will introduce a 1 second delay in starting sampling for the case where the main process is a python process and there aren't any children yet. 
I'll fix this up in a future PR though =)

**Comment by benfred** [comment]
Made that tweak here https://github.com/benfred/py-spy/pull/377

**Comment by IceTDrinker** [comment]
Thanks for the merge and the tweak, I was thinking the delay might be a problem but did not think about passing the -s flag on a program with an already running python interpreter !

Cheers

**Pull request merged**
