### PR TITLE
Fix Windows build and lint

### PR DESCRIPTION
**Pull request by zanieb**
@benfred regarding https://github.com/benfred/py-spy/pull/679#issuecomment-2405668108

Includes a few other changes as we debugged the cause of the failure.

### CODE REVIEW

**Review by benfred — APPROVED** [review]
Thanks for the PR!  The changes look good to me,

**Comment by benfred** [comment]
I'd like to get the windows CI working before merging - I realized I might have messed up the how python is installed in the last PR (moved setup-python to the wrong location in the GHA yaml), and am also testing out a tweak to fix in this other PR
  https://github.com/benfred/py-spy/pull/642

**Comment by zanieb** [comment]
Yeah agree. I'm pulling updates from my fork to see if one of those fixes the issue — I don't know what else I would have changed to make CI pass.

**Comment by zanieb** [comment]
It looks like you might have changed from Python 3.9 -> 3.11?

**Comment by benfred** [comment]
I'm sorta wondering if this is related to the python version being tested - I'm getting a different error with python 3.10 than with python 3.11 in CI, and I'm wondering if the working versions are with python 3.9. 

Because of how I messed up the setup python install, its possible that the 'fix clippy' pr we merged tested with python 3.9 (since the install for python 3.11 happened afterwards).

**Comment by benfred** [comment]
> It looks like you might have changed from Python 3.9 -> 3.11?

yeah, I'm testing now on #642 with 3.9 to see. 

The error with 3.10 was `called `Result::unwrap()` on an `Err` value: Failed to find a python interpreter in the .data section
` https://github.com/benfred/py-spy/actions/runs/11279360838/job/31369936001?pr=642 -  which might be the same as https://github.com/benfred/py-spy/issues/684 (so potentially a real issue with python 3.10 on windows, rather than a false positive in CI)

**Comment by zanieb** [comment]
Yeah https://github.com/benfred/py-spy/pull/685/commits/1d0ffc10f760f7d152e757b45f6d7de473345e3b resolves the error.

If you want, I can separate that commit from this pull request. Otherwise, it seems fine to merge this as a whole.

**Comment by benfred** [comment]
I'm good merging this as a whole - thanks for fixing. 

It does like there is an issue on windows with python 3.10+ that needs fixing =( - but  that doesn't need to be fixed in this PR.

**Pull request merged**
