### PR TITLE
Add option to output intermediate stacks

### PR DESCRIPTION
**Pull request by aparamon**
https://github.com/benfred/py-spy/issues/38
https://github.com/benfred/py-spy/issues/45

### CODE REVIEW

**Comment by aparamon** [comment]
@benfred Anything from my side needed to get this (and https://github.com/benfred/py-spy/pull/74) merged?

**Comment by okapies** [comment]
I really need this feature to integrate with other visualizers like speedscope.

**Comment by Norbo11** [comment]
Will this be merged at any point?

**Comment by dongx3** [comment]
@benfred any reason this PR not to be merged?

**Comment by 3tilley** [comment]
What's the status of this? I was looking to do something similar before I saw it

**Comment by benfred** [comment]
Thanks for the PR !

Sorry about the delay on getting back to you on this - I wasn't sure about customizing the flamegraph code more since it was taken from rbspy, and there was some potential licensing headaches w/ py-spy being GPL and rbspy being MIT (like I wanted to merge this code and some others into a common library and would be complicated to do that with changes from other people in the py-spy variant). I've relicensed this entire project to MIT so get around this with 0.2.0 - and I've also added this functionality there.

**Comment by xmo-odoo** [comment]
@benfred maybe #45 could be closed then?

**Pull request closed without merging**
