### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by andrewjcg**
```
warning: unexpected `cfg` condition name: `unwind`
  --> src/python_spy.rs:38:11
   |
38 |     #[cfg(unwind)]
   |           ^^^^^^ help: found config with similar value: `panic =
"unwind"`
   |
   = help: consider using a Cargo feature instead
   = help: or consider adding in `Cargo.toml` the `check-cfg` lint
config for the lint:
            [lints.rust]
            unexpected_cfgs = { level = "warn", check-cfg =
['cfg(unwind)'] }
   = help: or consider adding
`println!("cargo::rustc-check-cfg=cfg(unwind)");` to the top of the
`build.rs`
   = note: see
<https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html>
for more information about checking conditional configuration
```

### CODE REVIEW

**Review by benfred — APPROVED** [review]
Thanks for the PR - this is really helpful!

**Comment by zanieb** [comment]
As a note, I approached this quite differently in https://github.com/zanieb/py-spy/commit/045846adfefa7df17af52629c28be794ef044776 — the downside to that is that it requires a newer Cargo version in your cross-build images.

**Comment by benfred** [comment]
@zanieb nice! that does seem like a simpler change - 

updating the docker cross-build images is something we should do at some point, but I'm inclined to get this PR merged to unblock some other necessary changes.

**Comment by zanieb** [comment]
Definitely whatever works best for you.

The cross-build images [merge with the upstream](https://github.com/zanieb/rust-musl-cross-pyspy/commit/bf4e3d019d8e397a57864479465872ce5da0ae64) without conflict. I'm having some trouble building them though (mostly due to lack of understanding of how they're intended to be built).

**Comment by benfred** [comment]
> I'm having some trouble building them though (mostly due to lack of understanding of how they're intended to be built).

I  usually build with:

```
# x86_64-unknown-linux-musl
docker build -t benfred/rust-musl-cross:x86_64-musl .
# aarch64-unknown-linux-musl
docker build --build-arg TARGET=aarch64-unknown-linux-musl --build-arg RUST_MUSL_MAKE_CONFIG=config.mak -t benfred/rust-musl-cross:aarch64-musl .
# armv7-unknown-linux-musleabihf
docker build --build-arg TARGET=armv7-unknown-linux-musleabihf --build-arg RUST_MUSL_MAKE_CONFIG=config.mak.32 -t benfred/rust-musl-cross:armv7-musleabihf .
# i686-unknown-linux-musl
docker build --build-arg TARGET=i686-unknown-linux-musl --build-arg RUST_MUSL_MAKE_CONFIG=config.mak.32 -t benfred/rust-musl-cross:i686-musl .
# powerpc64le-unknown-linux-musl
docker build --build-arg TARGET=powerpc64le-unknown-linux-musl --build-arg RUST_MUSL_MAKE_CONFIG=config.mak --build-arg TOOLCHAIN=nightly -t benfred/rust-musl-cross:powerpc64le-musl .
```

(which is a subset of the upstream project, but all I need for py-spy).

**Comment by zanieb** [comment]
I saw the build script but I'm on an aarch64 mac so I can't run it locally. I'm [building them in GitHub instead](https://github.com/zanieb/rust-musl-cross-pyspy/blob/main/.github/workflows/publish.yml). I think I've got it mostly figured out now. I can open a pull request if you open your repository to contributions.

(Sorry for the unrelated discussion on this PR!)

**Comment by benfred** [comment]
>I saw the build script but I'm on an aarch64 mac so I can't run it locally. I'm [building them in GitHub instead](https://github.com/zanieb/rust-musl-cross-pyspy/blob/main/.github/workflows/publish.yml). I think I've got it mostly figured out now. I can open a pull request if you open your repository to contributions.

I would appreciate a PR here - thanks for updating this!

**Comment by benfred** [comment]
Also unrelated - but the windows build CI succeeded on this PR https://github.com/benfred/py-spy/actions/runs/11264051989/job/31323278597 but then immediately failed on the main branch =( https://github.com/benfred/py-spy/actions/runs/11264590823/job/31324954658 .

**Pull request merged**
